# Database connection properties
url=jdbc:postgresql://localhost:5432/sonaged
username=postgres
password=keane
driver=org.postgresql.Driver
changeLogFile=src/main/resources/config/liquibase/master.xml

outputChangeLogFile=src/main/resources/config/liquibase/changelog/1.1.0_schema.xml
# Hibernate configuration
#referenceUrl=hibernate:spring:sonaged.collecte.master.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceUrl=hibernate:spring:sonaged.collecte.master.model?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy